import { useEffect, useRef, useState, type ReactNode } from 'react'
import { BrowserMultiFormatReader } from '@zxing/browser'
import { Camera, Check, Code2, ExternalLink, LockKeyhole, Mail, MapPin, Phone, ScanLine, ShieldCheck, Sparkles, Upload, WandSparkles, X } from 'lucide-react'
import './App.css'
import type { CodeRecord, View } from './types'
import { classifyContent } from './utils/contentClassifier'
import CreateStudio from './components/CreateStudio'

const pages: { id: View; label: string; icon: typeof ScanLine }[] = [{ id: 'scan', label: 'Lector', icon: ScanLine }, { id: 'create', label: 'Creador', icon: WandSparkles }]
const formatNames: Record<string, string> = { QR_CODE: 'Código QR', CODE_128: 'Code 128', CODE_39: 'Code 39', EAN_13: 'EAN-13', DATA_MATRIX: 'Data Matrix', AZTEC: 'Aztec', PDF_417: 'PDF417' }

export default function App() {
  const [page, setPage] = useState<View>('scan'); const [toast, setToast] = useState('')
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }
  const add = (data: Omit<CodeRecord, 'id' | 'timestamp'>) => ({ ...data, id: crypto.randomUUID(), timestamp: Date.now() })
  return <div className="app"><aside className="sidebar"><Brand /><div className="nav-label">Herramientas</div><nav className="nav">{pages.map(({ id, label, icon: Icon }) => <button key={id} className={page === id ? 'active' : ''} onClick={() => setPage(id)}><Icon size={17} />{label}</button>)}</nav></aside><main className="main"><header className="topbar"><span className="crumb">CodeForge Studio / <b>{page === 'scan' ? 'Lector' : 'Creador'}</b></span><span className="top-status"><span /> Sin cuenta · Sin servidor</span></header><div className="content">{page === 'scan' ? <Scanner add={add} notify={notify} /> : <CreateStudio notify={notify} />}</div></main><nav className="mobile-nav">{pages.map(({ id, label, icon: Icon }) => <button key={id} className={page === id ? 'active' : ''} onClick={() => setPage(id)}><Icon size={18} />{label}</button>)}</nav>{toast && <div className="toast"><Check size={14} /> {toast}</div>}</div>
}
function Brand() { return <div className="brand"><div className="brand-mark">⌘</div><div>CodeForge <small>STUDIO</small></div></div> }
function Scanner({ add, notify }: { add: (data: Omit<CodeRecord, 'id' | 'timestamp'>) => CodeRecord; notify: (message: string) => void }) {
  const video = useRef<HTMLVideoElement>(null); const reader = useRef<BrowserMultiFormatReader | null>(null); const controls = useRef<{ stop: () => void } | null>(null); const [live, setLive] = useState(false); const [deviceId, setDeviceId] = useState(''); const [status, setStatus] = useState('Coloca un código dentro del marco'); const [error, setError] = useState(''); const [result, setResult] = useState<CodeRecord>()
  const stop = () => { controls.current?.stop(); controls.current = null; reader.current = null; (video.current?.srcObject as MediaStream | null)?.getTracks().forEach((track) => track.stop()); setLive(false) }
  const accept = (text: string, format: string) => { const item = add({ operation: 'scanned', codeFormat: format, content: text, contentType: classifyContent(text).type }); setResult(item); setStatus('Código detectado'); notify('Código leído correctamente'); return item }
  const acceptRef = useRef(accept); useEffect(() => { acceptRef.current = accept }, [accept])
  const start = async () => { try { setError(''); const devices = await BrowserMultiFormatReader.listVideoInputDevices(); const device = devices.find((item) => /back|rear|environment/i.test(item.label)) ?? devices[0]; if (!device) throw Error(); setDeviceId(device.deviceId); setLive(true) } catch { setError('No se pudo abrir la cámara. Revisa los permisos del navegador.') } }
  useEffect(() => { if (!live || !deviceId || !video.current) return; const instance = new BrowserMultiFormatReader(); reader.current = instance; void instance.decodeFromVideoDevice(deviceId, video.current, (code) => { if (code) { acceptRef.current(code.getText(), code.getBarcodeFormat().toString()); stop() } }).then((value) => { controls.current = value }).catch(() => { stop(); setError('No se pudo iniciar la cámara.') }); return () => { controls.current?.stop(); controls.current = null; reader.current = null } }, [live, deviceId])
  const image = async (file: File) => { setStatus('Analizando imagen...'); try { const url = URL.createObjectURL(file); const code = await new BrowserMultiFormatReader().decodeFromImageUrl(url); URL.revokeObjectURL(url); accept(code.getText(), code.getBarcodeFormat().toString()) } catch { setStatus('No se encontró un código compatible en la imagen.') } }
  useEffect(() => stop, [])
  return <><div className="eyebrow">Lector de códigos</div><h1>Escanea.<br /><span>Entiende al instante.</span></h1><p className="lead">Usa la cámara o sube una imagen para leer códigos QR y códigos de barras directamente en tu navegador.</p><div className="grid"><section className="panel"><div className="panel-title"><div><h2>Cámara</h2><span className="muted">Detección automática de formatos</span></div><span className="eyebrow">{live ? '● ACTIVA' : '○ INACTIVA'}</span></div><div className="scan-stage">{live && <video ref={video} muted playsInline />}{!live && <div className="stage-empty"><Camera size={28} /><span>{error || status}</span></div>}<div className="scan-frame"><div className="scan-line" /></div>{live && <span className="stage-label">{error || status}</span>}</div><div className="actions">{live ? <button className="secondary" onClick={stop}><X size={14} /> Detener cámara</button> : <button className="primary" onClick={start}><Camera size={15} /> Abrir cámara</button>}<label className="secondary"><Upload size={14} /> Subir imagen<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => event.target.files?.[0] && image(event.target.files[0])} /></label></div>{result && <ScanResult result={result} />}</section><section className="panel scan-info"><div className="panel-title"><div><h2>Lectura privada</h2><span className="muted">Sin cuentas ni procesamiento remoto</span></div><ShieldCheck size={20} color="#78e6c1" /></div><InfoRow icon={<LockKeyhole size={15} />} title="En tu dispositivo" text="La cámara y las imágenes se procesan localmente." /><InfoRow icon={<Sparkles size={15} />} title="Lectura inteligente" text="Reconoce enlaces, contactos, Wi-Fi, teléfonos y más." /><InfoRow icon={<Code2 size={15} />} title="Acción directa" text="Abre el contenido detectado con un solo clic." /></section></div></>
}
function ScanResult({ result }: { result: CodeRecord }) { const analysis = classifyContent(result.content); const action = getAction(result.content, analysis.type); return <div className="result"><div className="result-tag">CÓDIGO DETECTADO · {formatNames[result.codeFormat] ?? result.codeFormat}</div><div className="result-value">{result.content}</div><span className="result-type">{analysis.label}</span>{action && <a className="result-action" href={action.href} target={action.external ? '_blank' : undefined} rel={action.external ? 'noopener noreferrer' : undefined}><action.icon size={14} /> {action.label}{action.external && <ExternalLink size={12} />}</a>}</div> }
function getAction(content: string, type: ReturnType<typeof classifyContent>['type']) { if (type === 'url') { try { const url = new URL(content); if (url.protocol === 'http:' || url.protocol === 'https:') return { label: 'Abrir sitio web', href: url.href, external: true, icon: ExternalLink } } catch { return null } } if (type === 'email') return { label: 'Enviar correo', href: content.startsWith('mailto:') ? content : `mailto:${content}`, external: false, icon: Mail }; if (type === 'phone') return { label: 'Llamar', href: content.startsWith('tel:') ? content : `tel:${content}`, external: false, icon: Phone }; if (type === 'sms') return { label: 'Enviar mensaje', href: content.toLowerCase().startsWith('sms:') ? content : `sms:${content}`, external: false, icon: Mail }; if (type === 'geo') { const [lat, lon] = content.slice(4).split(','); if (lat && lon && Number.isFinite(Number(lat)) && Number.isFinite(Number(lon))) return { label: 'Abrir en mapas', href: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${lat},${lon}`)}`, external: true, icon: MapPin } } return null }
function InfoRow({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <div className="feature"><div className="feature-icon">{icon}</div><div><h3>{title}</h3><p>{text}</p></div></div> }
