import { useEffect, useRef, useState, type ReactNode } from 'react'
import { BrowserMultiFormatReader } from '@zxing/browser'
import QRCodeStyling from 'qr-code-styling'
import JsBarcode from 'jsbarcode'
import { Camera, Check, Code2, Copy, Download, History as HistoryIcon, Inspect, LockKeyhole, Moon, Search, ScanLine, Settings, ShieldCheck, Sparkles, Trash2, Upload, WandSparkles, X, Clipboard as ClipboardIcon } from 'lucide-react'
import './App.css'
import type { CodeRecord, View } from './types'
import { classifyContent } from './utils/contentClassifier'
import { loadHistory, saveHistory } from './services/storage'
import CreateStudio from './components/CreateStudio'

const pages: { id: View; label: string; icon: typeof ScanLine }[] = [{ id: 'scan', label: 'Scan', icon: ScanLine }, { id: 'create', label: 'Create', icon: WandSparkles }, { id: 'inspector', label: 'Inspector', icon: Inspect }, { id: 'history', label: 'History', icon: HistoryIcon }]
const names: Record<string, string> = { QR_CODE: 'QR Code', CODE_128: 'Code 128', EAN_13: 'EAN-13' }

export default function App() {
  const [page, setPage] = useState<View>('scan'); const [history, setHistory] = useState<CodeRecord[]>(loadHistory); const [selected, setSelected] = useState<CodeRecord>(); const [toast, setToast] = useState(''); const [light, setLight] = useState(false)
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }
  const add = (data: Omit<CodeRecord, 'id' | 'timestamp'>) => { const item = { ...data, id: crypto.randomUUID(), timestamp: Date.now() }; const next = [item, ...history]; setHistory(next); saveHistory(next); return item }
  const inspect = (item: CodeRecord) => { setSelected(item); setPage('inspector') }
  return <div className={light ? 'app light' : 'app'}><aside className="sidebar"><Brand /><div className="nav-label">Workspace</div><nav className="nav">{pages.map(({ id, label, icon: Icon }) => <button key={id} className={page === id ? 'active' : ''} onClick={() => setPage(id)}><Icon size={16} />{label}</button>)}</nav><div className="sidebar-bottom"><div className="privacy"><LockKeyhole size={14} /><span><b>Local-first</b><br />Your codes stay on this device.</span></div><button className="nav" onClick={() => setPage('settings')}><Settings size={14} /> Settings & About</button></div></aside><main className="main"><header className="topbar"><span className="crumb">CodeForge / <b>{pages.find((item) => item.id === page)?.label ?? 'Settings'}</b></span><div className="top-actions"><button className="icon-btn" aria-label="Toggle theme" onClick={() => setLight(!light)}><Moon size={15} /></button><button className="icon-btn" aria-label="Settings" onClick={() => setPage('settings')}><Settings size={15} /></button></div></header><div className="content">{page === 'scan' && <Scan add={add} inspect={inspect} notify={notify} />}{page === 'create' && <CreateStudio add={add} notify={notify} />}{page === 'inspector' && <Inspector item={selected ?? history[0]} notify={notify} />}{page === 'history' && <History items={history} inspect={inspect} remove={(id) => { const next = history.filter((item) => item.id !== id); setHistory(next); saveHistory(next) }} clear={() => { setHistory([]); saveHistory([]); notify('History cleared') }} />}{page === 'settings' && <SettingsPage light={light} />}</div></main><nav className="mobile-nav">{pages.map(({ id, label, icon: Icon }) => <button key={id} className={page === id ? 'active' : ''} onClick={() => setPage(id)}><Icon size={17} />{label}</button>)}</nav>{toast && <div className="toast"><Check size={14} /> {toast}</div>}</div>
}
function Brand() { return <div className="brand"><div className="brand-mark">⌘</div><div>CodeForge <small>STUDIO</small></div></div> }
function Scan({ add, inspect, notify }: { add: (data: Omit<CodeRecord, 'id' | 'timestamp'>) => CodeRecord; inspect: (item: CodeRecord) => void; notify: (message: string) => void }) {
  const video = useRef<HTMLVideoElement>(null); const reader = useRef<BrowserMultiFormatReader | null>(null); const controls = useRef<{ stop: () => void } | null>(null); const [live, setLive] = useState(false); const [deviceId, setDeviceId] = useState(''); const [status, setStatus] = useState('Position a code inside the frame'); const [error, setError] = useState(''); const [result, setResult] = useState<CodeRecord>()
  const stop = () => { controls.current?.stop(); controls.current = null; reader.current = null; (video.current?.srcObject as MediaStream | null)?.getTracks().forEach((track) => track.stop()); setLive(false); }
  const accept = (text: string, format: string) => { const item = add({ operation: 'scanned', codeFormat: format, content: text, contentType: classifyContent(text).type }); setResult(item); setStatus('Code detected'); notify('Code saved to history'); return item }
  const acceptRef = useRef(accept)
  useEffect(() => { acceptRef.current = accept }, [accept])
    const start = async () => { try { setError(''); const devices = await BrowserMultiFormatReader.listVideoInputDevices(); const device = devices.find((item) => /back|rear|environment/i.test(item.label)) ?? devices[0]; if (!device) throw Error(); setDeviceId(device.deviceId); setLive(true); } catch { setError('Camera unavailable. Check permissions or use image upload.') } }
    useEffect(() => { if (!live || !deviceId || !video.current) return; const instance = new BrowserMultiFormatReader(); reader.current = instance; void instance.decodeFromVideoDevice(deviceId, video.current, (code) => { if (code) { acceptRef.current(code.getText(), code.getBarcodeFormat().toString()); stop() } }).then((value) => { controls.current = value }).catch(() => { stop(); setError('Camera could not start. Check browser permissions.') }); return () => { controls.current?.stop(); controls.current = null; reader.current = null } }, [live, deviceId])
  const image = async (file: File) => { setStatus('Scanning image...'); try { const url = URL.createObjectURL(file); const code = await new BrowserMultiFormatReader().decodeFromImageUrl(url); URL.revokeObjectURL(url); accept(code.getText(), code.getBarcodeFormat().toString()) } catch { setStatus('No supported code found in this image.') } }
  useEffect(() => stop, [])
  return <><div className="eyebrow">Capture & decode</div><h1>Scan anything.<br /><span>Understand everything.</span></h1><p className="lead">Point your camera at a code or upload an image. Processing happens locally in your browser.</p><div className="grid"><section className="panel"><div className="panel-title"><div><h2>Live scanner</h2><span className="muted">Multi-format detection</span></div><span className="eyebrow">{live ? '● LIVE' : '○ IDLE'}</span></div><div className="scan-stage">{live && <video ref={video} muted playsInline />}<div className="scan-frame"><div className="scan-line" /></div><span className="stage-label">{error || status}</span></div><div className="actions">{live ? <button className="secondary" onClick={stop}><X size={14} /> Stop camera</button> : <button className="primary" onClick={start}><Camera size={15} /> Start camera</button>}<label className="secondary"><Upload size={14} /> Upload image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => event.target.files?.[0] && image(event.target.files[0])} /></label></div>{result && <div className="result"><div className="result-tag">SUCCESSFULLY DETECTED · {names[result.codeFormat] ?? result.codeFormat}</div><div className="result-value">{result.content}</div><button className="secondary" onClick={() => inspect(result)}><Inspect size={14} /> Inspect result</button></div>}</section><section className="panel"><div className="panel-title"><div><h2>Built for privacy</h2><span className="muted">A calmer way to scan</span></div><ShieldCheck size={20} color="#78e6c1" /></div><Feature icon={<LockKeyhole size={15} />} title="Local by default" text="Camera frames and images are processed on your device." /><Feature icon={<Sparkles size={15} />} title="Smart interpretation" text="URLs, Wi-Fi, contacts and locations are recognized instantly." /><Feature icon={<HistoryIcon size={15} />} title="Your history, yours" text="Keep useful results close with private browser storage." /><div className="stats"><div className="stat"><strong>12+</strong><span>Formats</span></div><div className="stat"><strong>0</strong><span>Accounts</span></div><div className="stat"><strong>100%</strong><span>Client-side</span></div></div></section></div></>
}
function Feature({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <div className="feature"><div className="feature-icon">{icon}</div><div><h3>{title}</h3><p>{text}</p></div></div> }
export function Create({ add, notify }: { add: (data: Omit<CodeRecord, 'id' | 'timestamp'>) => CodeRecord; notify: (message: string) => void }) {
  const [barcodeMode, setBarcodeMode] = useState(false); const [value, setValue] = useState('https://codeforge.studio'); const [type, setType] = useState('url'); const [barcode, setBarcode] = useState('CODEFORGE-2026'); const qrRef = useRef<HTMLDivElement>(null); const svgRef = useRef<SVGSVGElement>(null); const [qr, setQr] = useState<QRCodeStyling>()
  useEffect(() => { if (!barcodeMode && qrRef.current) { const instance = new QRCodeStyling({ width: 270, height: 270, data: value || ' ', dotsOptions: { color: '#10251e', type: 'rounded' }, backgroundOptions: { color: '#f5f3ed' }, margin: 12 }); qrRef.current.innerHTML = ''; instance.append(qrRef.current); setQr(instance) } }, [barcodeMode, value])
  useEffect(() => { if (barcodeMode && svgRef.current) JsBarcode(svgRef.current, barcode || ' ', { format: 'CODE128', width: 2, height: 100, margin: 12, background: '#f5f3ed', lineColor: '#10251e' }) }, [barcodeMode, barcode])
  const save = () => { add({ operation: 'generated', codeFormat: barcodeMode ? 'CODE_128' : 'QR_CODE', content: barcodeMode ? barcode : value, contentType: classifyContent(value).type }); notify('Code saved to history') }
  return <><div className="eyebrow">Create a code</div><h1>Your ideas,<br /><span className="gold">made scannable.</span></h1><p className="lead">Generate polished QR codes and barcodes with a live preview.</p><div className="tabs"><button className={!barcodeMode ? 'active' : ''} onClick={() => setBarcodeMode(false)}><Code2 size={13} /> QR code</button><button className={barcodeMode ? 'active' : ''} onClick={() => setBarcodeMode(true)}><Code2 size={13} /> Barcode</button></div><div className="grid"><section className="panel"><div className="panel-title"><h2>Configure</h2><Sparkles size={17} color="#f1b35b" /></div>{!barcodeMode ? <div className="form-grid"><div className="field"><label>CONTENT TYPE</label><select value={type} onChange={(event) => { setType(event.target.value); setValue(event.target.value === 'url' ? 'https://codeforge.studio' : '') }}><option value="url">Website URL</option><option value="text">Plain text</option><option value="wifi">Wi-Fi network</option><option value="email">Email address</option><option value="phone">Phone number</option><option value="geo">Location</option></select></div><div className="field"><label>PAYLOAD</label><textarea value={value} onChange={(event) => setValue(event.target.value)} /></div><label className="check"><input type="checkbox" defaultChecked /> High error correction</label><button className="primary" onClick={save}><Download size={14} /> Save to history</button></div> : <div className="form-grid"><div className="field"><label>FORMAT</label><select><option>Code 128</option><option>EAN-13</option><option>CODE39</option></select></div><div className="field"><label>VALUE</label><input value={barcode} onChange={(event) => setBarcode(event.target.value)} /></div><button className="primary" onClick={save}><Download size={14} /> Save to history</button></div>}</section><section className="panel"><div className="panel-title"><div><h2>Preview</h2><span className="muted">Updates as you type</span></div><button className="icon-btn" aria-label="Download" onClick={() => { qr?.download({ name: 'codeforge-code', extension: 'png' }); notify('Export started') }}><Download size={15} /></button></div><div className="preview">{barcodeMode ? <svg ref={svgRef} aria-label="Generated barcode" /> : <div ref={qrRef} aria-label="Generated QR code" />}</div></section></div></>
}
function Inspector({ item, notify }: { item?: CodeRecord; notify: (message: string) => void }) { if (!item) return <Empty title="Nothing to inspect yet" text="Scan or create a code first." icon={<Inspect size={26} />} />; const analysis = classifyContent(item.content); return <><div className="eyebrow">Code inspector</div><h1>Look closer.</h1><p className="lead">A readable view of your code and its useful next actions.</p><div className="inspector-grid"><section className="panel"><div className="panel-title"><div><h2>{analysis.label}</h2><span className="muted">{names[item.codeFormat] ?? item.codeFormat}</span></div><button className="secondary" onClick={() => navigator.clipboard?.writeText(item.content).then(() => notify('Copied to clipboard'))}><Copy size={14} /> Copy</button></div><div className="detail-list">{Object.entries(analysis.details).filter(([, value]) => value).map(([key, value]) => <div className="detail" key={key}><span>{key}</span><strong>{value}</strong></div>)}</div></section><section className="panel"><div className="panel-title"><h2>Raw content</h2><ClipboardIcon size={17} color="#78e6c1" /></div><div className="raw">{item.content}</div></section></div></> }
function History({ items, inspect, remove, clear }: { items: CodeRecord[]; inspect: (item: CodeRecord) => void; remove: (id: string) => void; clear: () => void }) { const [query, setQuery] = useState(''); const filtered = items.filter((item) => item.content.toLowerCase().includes(query.toLowerCase())); return <><div className="eyebrow">Your workspace</div><div className="split"><div><h1>History.</h1><p className="lead">Recent scans and creations, stored privately in your browser.</p></div>{items.length > 0 && <button className="danger" onClick={() => window.confirm('Clear all local history?') && clear()}><Trash2 size={14} /> Clear history</button>}</div><section className="panel"><div className="field"><label><Search size={12} /> SEARCH HISTORY</label><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search content..." /></div>{filtered.length ? <div className="history-list">{filtered.map((item) => <div className="history-item" key={item.id}><div className="history-symbol"><ScanLine size={15} /></div><div className="history-copy"><strong>{names[item.codeFormat] ?? item.codeFormat} <span className="muted">· {item.operation}</span></strong><p>{item.content}</p><small>{new Date(item.timestamp).toLocaleString()}</small></div><div className="history-actions"><button aria-label="Inspect" onClick={() => inspect(item)}><Inspect size={15} /></button><button aria-label="Delete" onClick={() => remove(item.id)}><Trash2 size={15} /></button></div></div>)}</div> : <Empty title={query ? 'No matching codes' : 'Your recent codes will appear here.'} text="Scan something new or create your first code." icon={<HistoryIcon size={26} />} />}</section></> }
function SettingsPage({ light }: { light: boolean }) { return <><div className="eyebrow">Workspace preferences</div><h1>Quietly powerful.</h1><p className="lead">A focused toolkit for turning machine-readable data into useful context.</p><div className="grid"><section className="panel"><div className="panel-title"><h2>About CodeForge</h2><ShieldCheck size={17} color="#78e6c1" /></div><p className="muted" style={{ lineHeight: 1.8 }}>Camera frames, uploaded images and history remain in your browser. No account or server processing is required.</p><div className="detail-list"><div className="detail"><span>Theme</span><strong>{light ? 'Light' : 'Dark'} mode</strong></div><div className="detail"><span>Storage</span><strong>Local browser storage</strong></div></div></section><section className="panel"><div className="panel-title"><h2>Supported formats</h2><Code2 size={17} color="#f1b35b" /></div><p className="muted" style={{ lineHeight: 1.8 }}>Scanning delegates format support to ZXing and depends on browser/device support. Generation includes QR Code and Code 128.</p></section></div></> }
function Empty({ title, text, icon }: { title: string; text: string; icon: ReactNode }) { return <div className="empty"><div>{icon}</div><b>{title}</b><span>{text}</span></div> }
